---


local_runner: false
push_cache: true
pipeline: "master"
publishing_pipeline: true
skip_build: false
repository: "cos-tests"
publish_cloud: false
cache_repository: "cos-tests-build"
organization: "quay.io/mudler"
skip_tests: true
flavors: ["opensuse"]
skip_tests_flavor: ["fedora","ubuntu"]
skip_images_flavor: ["fedora","ubuntu"]
release_flavor: ["opensuse"]

on: 
  push: 
    branches: ["release_pipeline"]
    tags:
      - "v*"